=== Dehamo/Data-mining/XML-JSON/exercices/biblio-v1.dtd
<!ELEMENT bibliographie (livres|articles)+>
    <!ELEMENT livres (livre)*>
    <!ATTLIST livre id CDATA #REQUIRED>
    <!ELEMENT livre (titre, noms_auteurs, tome, edition)>
    <!ELEMENT titre (#PCDATA)>
    <!ELEMENT noms_auteurs (#PCDATA)>
    <!ELEMENT tome (nombre_pages)>
    <!ATTLIST tome id CDATA #IMPLIED name CDATA #IMPLIED>
    <!ELEMENT nombre_pages (#PCDATA)>
    <!ELEMENT edition (editeur, lieu_edition, lieu_impression, ISBN)>
    <!ELEMENT editeur (#PCDATA)>
    <!ELEMENT lieu_edition (#PCDATA)>
    <!ELEMENT lieu_impression (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT articles (article)*>
    <!ELEMENT article (titre, noms_auteurs, publication)>
    <!ATTLIST article id CDATA #REQUIRED>
    <!ELEMENT publication (journal, numero_journal, annee, numero_pages, avis?)>
    <!ELEMENT journal (#PCDATA)>
    <!ELEMENT numero_journal (#PCDATA)>
    <!ELEMENT annee (#PCDATA)>
    <!ELEMENT numero_pages (#PCDATA)>
    <!ELEMENT avis (#PCDATA)>

=== Dehamo/Data-mining/XML-JSON/exercices/biblio-v1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bibliographie SYSTEM "biblio-v1.dtd">

<bibliographie>
    <livres>
        <livre id="numero du livre"> 
            <titre></titre>
            <noms_auteurs></noms_auteurs>
            <tome id="numéro du tome" name="nom du tome">
                <nombre_pages></nombre_pages>
            </tome>
            <edition>
                <editeur></editeur>
                <lieu_edition></lieu_edition>
                    <lieu_impression></lieu_impression>
                    <ISBN></ISBN>
            </edition>
        </livre>
    </livres>
    <articles>
        <article id="numéro de l'article">
            <titre></titre>
            <noms_auteurs></noms_auteurs>
            <publication>
                <journal></journal>
                <numero_journal></numero_journal>
                <annee></annee>
                <numero_pages></numero_pages>
                <avis></avis>
            </publication>
        </article>
    </articles>
</bibliographie>
