=== Dehamo/Data-mining/XML-JSON/exercices/biblio-v2.dtd
<!ELEMENT bibliographie (livres|articles)+>
    <!ELEMENT livres (livre)*>
    <!ATTLIST livre id CDATA #REQUIRED>
    <!ELEMENT livre (titre, noms_auteurs, tome, edition)>
    <!ELEMENT titre EMPTY>
    <!ATTLIST titre soustitre CDATA #IMPLIED>
    <!ELEMENT noms_auteurs (#PCDATA)>
    <!ELEMENT tome EMPTY>
    <!ATTLIST tome id CDATA #IMPLIED name CDATA #IMPLIED nb_pages CDATA #REQUIRED soustitre CDATA #IMPLIED>
    <!ELEMENT edition (editeur, lieu_edition, lieu_impression, ISBN)>
    <!ELEMENT editeur (#PCDATA)>
    <!ELEMENT lieu_edition (#PCDATA)>
    <!ELEMENT lieu_impression (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT articles (article)*>
    <!ELEMENT article (titre, noms_auteurs, publication)>
    <!ATTLIST article id CDATA #REQUIRED>
    <!ELEMENT publication (journal, numero_journal, numero_pages, avis?)>
    <!ATTLIST publication annee (2000|2001|2002|avant_2000|inconnue) "inconnue">
    <!ATTLIST journal nom_journal CDATA "Feuille de Chou">
    <!ELEMENT journal (#PCDATA)>
    <!ELEMENT numero_journal (#PCDATA)>
    <!ELEMENT numero_pages (#PCDATA)>
    <!ELEMENT avis (#PCDATA)>

=== Dehamo/Data-mining/XML-JSON/exercices/biblio-v2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bibliographie SYSTEM "biblio-v2.dtd">

<bibliographie>
    <livres>
        <livre id="numero du livre"> 
            <titre soustitre="sous-titre du livre"></titre>
            <noms_auteurs></noms_auteurs>
            <tome id="numéro du tome" name="nom du tome" nb_pages="nombre de pages" soustitre="sous-titre du tome"></tome>
            <edition>
                <editeur></editeur>
                <lieu_edition></lieu_edition>
                <lieu_impression></lieu_impression>
                <ISBN></ISBN>
            </edition>
        </livre>
    </livres>
    <articles>
        <article id="numéro de l'article">
            <titre soustitre="sous-titre de l'article"></titre>
            <noms_auteurs></noms_auteurs>
            <publication annee="inconnue">
                <journal nom_journal="Feuille de Chou"></journal>
                <numero_journal></numero_journal>
                <numero_pages></numero_pages>
                <avis></avis>
            </publication>
        </article>
    </articles>
</bibliographie>
